-- AlterEnum
ALTER TYPE "TaskType" ADD VALUE 'PSS_DEFENSIVE';
ALTER TYPE "TaskType" ADD VALUE 'PSS_OPS';
ALTER TYPE "TaskType" ADD VALUE 'PSS_OFFENSIVE';
ALTER TYPE "TaskType" ADD VALUE 'PSS_PRODUCT';
